# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'components-IOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for components-IOS
  pod 'SnapKit', '~> 3.0.0'

  post_install do |installer|
      installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['ENABLE_BITCODE'] = 'NO'
              config.build_settings['ARCHS'] = 'arm64'
              end
          if ['SnapKit'].include? target.name
              target.build_configurations.each do |config|
                  config.build_settings['SWIFT_VERSION'] = '3.2'
            end
        end
    end
  end
end
